#!/usr/bin/env python3
"""
Rebuild the site's doc pages from their source in caid-benchmark.

The explanatory note and the instruction live in one place, `docs/` of
revenue7-eng/caid-benchmark. This script derives the site copies from them, so
the text is edited once and never diverges. The differences the site needs are
declared below and are of three kinds only: a Jekyll header, links rewritten to
site pages, and a few site-only sentences.

Every rewrite and every insertion is anchored on an exact string. A missing
anchor aborts the build rather than silently dropping the change, which is what
makes this safe to run unattended.

Usage:
    python build_docs.py            # fetch from GitHub
    python build_docs.py --local ../caid-benchmark
"""
import argparse
import os
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = "https://raw.githubusercontent.com/revenue7-eng/caid-benchmark/main/docs/{}"

REPORT_CARDS = "[Report Cards](evidence.html)"
STANDARD = "[Assessment Standard](standard.html)"
GH = "https://github.com/revenue7-eng/caid-benchmark/blob/main/{}"

DOCS = {
    "how-it-works.md": {
        "title": "How it works",
        "nav_order": 2,
        "h1_from": "# CAID: how the measurement works",
        "h1_to": "# How the measurement works",
        "pdf": "../assets/pdf/how-it-works.pdf",
        "rewrites": [
            ("**The protocol** is [`PROTOCOL.md`](../PROTOCOL.md) in this repository, which lists",
             "**The protocol** is the [Assessment Standard](../docs/standard.html), which lists"),
            ("Open [`PROTOCOL.md`](../PROTOCOL.md) and the code",
             "Open [`PROTOCOL.md`](" + GH.format("PROTOCOL.md") + ") and the code"),
        ],
        "inserts": [
            ("**The reference run** is the first public measurement, May 2026: 26 models across five providers. The examples below refer to it.",
             " Current per-model numbers are on the [Report Cards](../docs/evidence.html)."),
        ],
    },
    "run-it-yourself.md": {
        "title": "Run it yourself",
        "nav_order": 4,
        "h1_from": "# CAID: running it yourself",
        "h1_to": "# Running it yourself",
        "pdf": "../assets/pdf/run-it-yourself.pdf",
        "rewrites": [
            ("means meeting every MUST clause in `PROTOCOL.md`. Checklist in section 10.",
             "means meeting every MUST clause in the " + STANDARD + ". Checklist in section 10."),
            ("Full wording in [`PROTOCOL.md`](../PROTOCOL.md).",
             "Full wording in the " + STANDARD + " and in [`PROTOCOL.md`](" + GH.format("PROTOCOL.md") + ")."),
            ("| [`PROTOCOL.md`](../PROTOCOL.md) |",
             "| [`PROTOCOL.md`](" + GH.format("PROTOCOL.md") + ") |"),
            ("| [`REPORT_v1.3.md`](../REPORT_v1.3.md) |",
             "| [`REPORT_v1.3.md`](" + GH.format("REPORT_v1.3.md") + ") |"),
            ("| [`REPORT_v1.2.md`](../REPORT_v1.2.md) |",
             "| `REPORT_v1.2.md` |"),
        ],
        "inserts": [
            ("This is the cheapest check available: anyone can recompute the published numbers in seconds, running nothing and paying nothing.",
             " The per-model figures they should match are on the " + REPORT_CARDS + "."),
        ],
    },
}


def fetch(name, local):
    if local:
        path = os.path.join(local, "docs", name)
        if not os.path.exists(path):
            sys.exit(f"Source not found: {path}")
        with open(path, encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(RAW.format(name)) as r:
        return r.read().decode("utf-8")


def derive(name, spec, src):
    if spec["h1_from"] not in src:
        sys.exit(f"{name}: heading '{spec['h1_from']}' not found. "
                 "The source changed shape; update DOCS in build_docs.py.")
    body = src.replace(spec["h1_from"], spec["h1_to"], 1)

    for old, new in spec["rewrites"]:
        if old not in body:
            sys.exit(f"{name}: rewrite anchor not found:\n  {old[:90]}\n"
                     "Either the source changed or the rewrite is obsolete.")
        body = body.replace(old, new)

    for anchor, addition in spec["inserts"]:
        if anchor not in body:
            sys.exit(f"{name}: insert anchor not found:\n  {anchor[:90]}\n"
                     "Either the source changed or the insertion is obsolete.")
        body = body.replace(anchor, anchor + addition, 1)

    header = (
        "---\n"
        f'title: "{spec["title"]}"\n'
        f'nav_order: {spec["nav_order"]}\n'
        "---\n\n"
        "<!-- Generated by build_docs.py from caid-benchmark/docs/"
        f"{name}. Edits here are overwritten; change the source. -->\n\n"
    )
    lead, rest = body.split("\n", 1)
    return f"{header}{lead}\n\n[Download as PDF]({spec['pdf']})\n{rest}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--local", default=None,
                    help="Path to a caid-benchmark checkout, instead of fetching")
    ap.add_argument("--check", action="store_true",
                    help="Compare against what is on disk and report, writing nothing")
    args = ap.parse_args()

    changed = []
    for name, spec in DOCS.items():
        out = derive(name, spec, fetch(name, args.local))
        dest = os.path.join(HERE, "docs", name)
        current = None
        if os.path.exists(dest):
            with open(dest, encoding="utf-8") as f:
                current = f.read()
        if current == out:
            print(f"{name}: up to date")
            continue
        changed.append(name)
        if args.check:
            print(f"{name}: DIFFERS from source")
        else:
            with open(dest, "w", encoding="utf-8") as f:
                f.write(out)
            print(f"{name}: rewritten from source")

    if args.check and changed:
        sys.exit(f"Out of date: {', '.join(changed)}. Run build_docs.py.")


if __name__ == "__main__":
    main()
